name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:

  - type: textarea
    id: reproducer
    attributes:
      label: Reproducer
      description: Provide a minimal reproducible example, if possible. This helps us understand and reproduce the issue. You can check out the HttpClient profiler panel to copy the curl command if needed.
      placeholder: ex. A curl command or small script
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of the bug, including any relevant context or error messages.
      placeholder: Describe the issue in detail...
    validations:
      required: true

  - type: input
    id: gotenberg_version
    attributes:
      label: Gotenberg Version
      description: Specify the version of Gotenberg you are using.
      placeholder: ex. 8.3.1
    validations:
      required: true

  - type: input
    id: gotenberg_bundle_version
    attributes:
      label: Gotenberg Bundle Version
      description: Specify the version of the Gotenberg bundle you are using.
      placeholder: ex. 0.3.1
    validations:
      required: false
