<?php

namespace Sensiolabs\GotenbergBundle\Tests\Integration\Pdf;

use Sensiolabs\GotenbergBundle\GotenbergPdfInterface;
use Sensiolabs\GotenbergBundle\Tests\Integration\AbstractGotenbergIntegrationTestCase;

final class HtmlPdfTest extends AbstractGotenbergIntegrationTestCase
{
    public function testItGeneratesPdfFromRawHtml(): void
    {
        /** @var GotenbergPdfInterface $gotenberg */
        $gotenberg = static::getContainer()->get(GotenbergPdfInterface::class);
        $result = $gotenberg
            ->html()
            ->fileName('integration-html-pdf')
            ->contentRaw('<html><body><h1>Integration PDF</h1><p>Generated by Gotenberg.</p></body></html>')
            ->generate()
        ;

        $this->assertBinaryFileResult($result, 'application/pdf', '.pdf');
    }
}
