name: 'Documentation'

on:
  push:
    branches: ['main', '1.x']
  pull_request:
    branches: ['main', '1.x']

permissions:
  contents: 'read'

jobs:

  builders-api:
    name: 'Builders API'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'

      - id: 'generate-docs-patch'
        name: 'Generate docs'
        uses: 'dagger/dagger-for-github@v8.2.0'
        with:
          version: 'latest'
          call: 'generate-docs as-patch contents'
          dagger-flags: '--silent'
        env:
          DAGGER_NO_NAG: '1'

      - name: 'Check documentation'
        run: |
          echo '${{ steps.generate-docs-patch.outputs.output }}' | git apply --allow-empty
          DIFF=$(git status --short --renames ./docs)
          if [[ $DIFF != '' ]]; then
            echo "::warning::Builders API documentation is not up to date. Please run \"dagger call generate-docs\""
            echo "::warning::$DIFF"
            exit 1
          fi
