name: 'Documentation'

on:
  push:
    branches: ['main', '1.x']
  pull_request:
    branches: ['main', '1.x']

permissions:
  contents: 'read'

jobs:

  builders-api:
    name: 'Builders API'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - id: 'generate-docs-patch'
        name: 'Generate docs'
        uses: dagger/dagger-for-github@27b130bf0f79a7f6fbbbe0fbca6760dc9bb40a77 # v8.4.1
        with:
          version: 'latest'
          call: 'generate-docs'
          dagger-flags: '--silent --auto-apply'
        env:
          DAGGER_NO_NAG: '1'

      - name: 'Check documentation'
        run: |
          DIFF=$(git status --short --renames ./docs)
          if [[ $DIFF != '' ]]; then
            echo "::warning::Builders API documentation is not up to date. Please run \"dagger --auto-apply call generate-docs\""
            echo "::warning::$DIFF"
            exit 1
          fi
