name: 'Unit Tests'

on:
  push:
    branches: ['main', '1.x']
  pull_request:
    branches: ['main', '1.x']
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: 'read'

jobs:
  setup:
    name: 'Setup matrix'
    runs-on: 'ubuntu-latest'
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: 'actions/checkout@v4'
      - id: 'set-matrix'
        run: |
          echo "matrix=$(jq -c '.' ./.dagger/src/matrix-versions.json)" >> $GITHUB_OUTPUT

  test:
    name: 'Build and Test - ${{ matrix.name }}'
    runs-on: 'ubuntu-latest'
    needs: 'setup'
    strategy:
      matrix:
        include: ${{ fromJson(needs.setup.outputs.matrix) }}
    continue-on-error: ${{ matrix.allow-failure }}
    steps:
      - uses: 'actions/checkout@v4'

      - name: 'Cache Dagger'
        uses: 'actions/cache@v4'
        with:
          path: |
            ~/.config/dagger
            ~/.cache/dagger
          key: ${{ runner.os }}-dagger-${{ hashFiles('dagger.json', '.dagger/src/**') }}
          restore-keys: |
            ${{ runner.os }}-dagger-

      - name: 'Run test suite'
        uses: 'dagger/dagger-for-github@8.0.0'
        with:
          version: "latest"
          call: "test --symfony-version '${{ matrix.symfony-version }}' --php-version '${{ matrix.php }}' --minimum-stability '${{ matrix.minimum-stability }}' phpunit"
          dagger-flags: '--silent'
        env:
          DAGGER_NO_NAG: '1'

  composer:
    name: 'Validate composer files and dependencies'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'

      - name: 'Cache Dagger'
        uses: 'actions/cache@v4'
        with:
          path: |
            ~/.config/dagger
            ~/.cache/dagger
          key: ${{ runner.os }}-dagger-${{ hashFiles('dagger.json', '.dagger/src/**') }}
          restore-keys: |
            ${{ runner.os }}-dagger-

      - name: 'Validate dependencies'
        uses: 'dagger/dagger-for-github@8.0.0'
        with:
          version: "latest"
          call: "test validate-dependencies"
          dagger-flags: '--silent'
        env:
          DAGGER_NO_NAG: '1'
