name: 'Doc URLS test'

on:
  push:
    branches: [ 'main', '1.x' ]
  pull_request:
    branches: [ 'main', '1.x' ]
  schedule:
    - cron: '0 1 1 * *'

jobs:

  check:
    name: 'Validate URL docs'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'

      - name: 'Validate URLS into PhpDoc'
        uses: 'dagger/dagger-for-github@8.0.0'
        with:
          version: 'latest'
          call: 'test validate-url-doc'
          dagger-flags: '--silent'
        env:
          DAGGER_NO_NAG: '1'
